# Generated by Django 4.1.5 on 2023-01-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "cl_person_id",
                    models.IntegerField(
                        help_text="The person id from Courtlistener db."
                    ),
                ),
                (
                    "name_first",
                    models.CharField(
                        help_text="The first name of this person.",
                        max_length=50,
                    ),
                ),
                (
                    "name_middle",
                    models.CharField(
                        blank=True,
                        help_text="The middle name or names of this person",
                        max_length=50,
                    ),
                ),
                (
                    "name_last",
                    models.CharField(
                        db_index=True,
                        help_text="The last name of this person",
                        max_length=50,
                    ),
                ),
                (
                    "name_suffix",
                    models.CharField(
                        help_text="Any suffixes that this person's name may have",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
