# Generated by Django 4.1.5 on 2023-01-27 00:45

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text="Name of the service", max_length=100
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        help_text="Name of the account", max_length=100
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        help_text="Service's ID number, username, etc. for the account, if applicable",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Disabled by default; must enable manually",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="user",
            field=models.ManyToManyField(
                help_text="Users that belong to the channel",
                related_name="channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
