# Generated by Django 4.1.6 on 2023-02-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_filingwebhookevent_and_more"),
        ("channel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        help_text="The object's id returned by Twitter/Mastodon/etc's API"
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, help_text="The post content"),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="channel.channel",
                    ),
                ),
                (
                    "filing_webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="subscription.filingwebhookevent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
