# Generated by Django 4.1.7 on 2023-03-22 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("channel", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that belong to the channel",
                related_name="channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
