# Generated by Django 4.1.7 on 2023-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0004_group_channel_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="access_token",
            field=models.TextField(
                default="",
                help_text="Access Tokens of the account that the bot is making the request on behalf of",
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="access_token_secret",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Access Tokens Secret of the account that the bot is making the request on behalf of",
            ),
        ),
    ]
