# Generated by Django 4.1.7 on 2023-06-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0005_channel_access_token_channel_access_token_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="overview",
            field=models.TextField(
                default="",
                help_text="Short description of the purpose of this group",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                default="", help_text="A generated path for this item"
            ),
        ),
    ]
