# Generated by Django 4.2.7 on 2023-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0007_group_border_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="service",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Twitter"), (2, "Mastodon"), (3, "Bluesky")],
                help_text="Type of the service",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="object_id",
            field=models.CharField(
                help_text="The object's id returned by Twitter/Mastodon/etc's API"
            ),
        ),
    ]
