# Generated by Django 5.1.1 on 2024-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0008_alter_channel_service_alter_post_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="service",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Twitter"),
                    (2, "Mastodon"),
                    (3, "Bluesky"),
                    (4, "Threads"),
                ],
                help_text="Type of the service",
            ),
        ),
    ]
