# Generated by Django 4.1.5 on 2023-01-20 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        help_text="Name of the service", max_length=100
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        help_text="Name of the account", max_length=100
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        help_text="Service's ID number, username, etc. for the account, if applicable",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Disabled by default; must enable manually",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        help_text="Users that belong to the channel",
                        related_name="channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The main body of each status update posted."
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        help_text="Foreign Key to the Channel object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="channels.channel",
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        help_text="Foreign Key to the Docket object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docket",
                        to="cases.docket",
                    ),
                ),
                (
                    "docket_entry",
                    models.ForeignKey(
                        help_text="Foreign Key to the DocketEntry object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docket_entries",
                        to="cases.docketentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
