# Generated by Django 4.1.7 on 2023-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="affiliation",
            field=models.TextField(
                blank=True, help_text="User's affiliations"
            ),
        ),
    ]
