# Generated by Django 4.1.7 on 2023-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_affiliation_noop"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_key",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="The user has confirmed their email address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="The time and date when the user's activation_key expires",
                null=True,
            ),
        ),
    ]
