# Generated by Django 4.1.7 on 2023-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_activation_key_user_email_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activation_key",
            field=models.CharField(default="", max_length=64),
        ),
    ]
