# Generated by Django 4.1.7 on 2023-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_activation_key_user_email_confirmed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activation_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="key_expires",
        ),
    ]
