# Generated by Django 4.1.6 on 2023-02-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0002_post"),
        ("subscription", "0002_filingwebhookevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="pacer_court_id",
        ),
        migrations.AddField(
            model_name="filingwebhookevent",
            name="description",
            field=models.TextField(
                blank=True, help_text="The document description"
            ),
        ),
        migrations.AddField(
            model_name="filingwebhookevent",
            name="post",
            field=models.ManyToManyField(
                blank=True,
                help_text="The posts generated after the event is handled",
                related_name="filing_webhook_events",
                through="channel.Post",
                to="channel.channel",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cl_slug",
            field=models.SlugField(
                blank=True,
                help_text="URL that the document should map to (the slug)",
                max_length=75,
            ),
        ),
    ]
