# Generated by Django 4.1.6 on 2023-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0003_remove_subscription_pacer_court_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filingwebhookevent",
            old_name="description",
            new_name="short_description",
        ),
        migrations.AddField(
            model_name="filingwebhookevent",
            name="long_description",
            field=models.TextField(
                blank=True, help_text="The docket entry's description"
            ),
        ),
    ]
