# Generated by Django 4.1.7 on 2023-05-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0004_group_channel_group"),
        ("subscription", "0007_alter_filingwebhookevent_status_noop"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="channel",
            field=models.ManyToManyField(
                blank=True,
                help_text="Channels where a post related to this docket should be created",
                related_name="subscriptions",
                to="channel.channel",
            ),
        ),
    ]
