# Generated by Django 4.1.7 on 2023-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0003_alter_channel_user"),
        ("subscription", "0007_alter_filingwebhookevent_status_noop"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="channel",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of channels where a post related to this docket should be created",
                related_name="Subscription",
                to="channel.channel",
            ),
        ),
    ]
