# Generated by Django 4.1.7 on 2023-06-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0008_subscription_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="article_url",
            field=models.URLField(
                blank=True, default="", help_text="Link to a news article"
            ),
        ),
    ]
