# Generated by Django 4.1.7 on 2023-03-30 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Initial amount of money given by the sponsor",
                        max_digits=10,
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of money that's left to buy documents",
                        max_digits=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user sponsoring the Bot",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Sponsorship"),
                            (2, "Document Purchase"),
                            (3, "Adjustment"),
                        ],
                        default=1,
                        help_text="The type of the transaction. Possible values are: (1): Sponsorship, (2): Document Purchase, (3): Adjustment",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of money spent/received in the transaction",
                        max_digits=10,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="More information about the transaction"
                    ),
                ),
                (
                    "sponsorship",
                    models.ForeignKey(
                        help_text="Sponsorship record related to the transaction",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="sponsorship.sponsorship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with the transaction",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
