# Generated by Django 4.1.7 on 2023-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sponsorship", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="watermark_message",
            field=models.CharField(
                blank=True,
                help_text="Short message to include in document's thumbnails",
                max_length=100,
            ),
        ),
    ]
