# Generated by Django 5.1.1 on 2024-12-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="If another config is currently active, enabling this one will deactivate the first one.",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "button_text",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("button_link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
