# Generated by Django 5.1.1 on 2024-12-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="If another config is currently active, enabling this one will deactivate the first one.",
                    ),
                ),
                ("banner_title", models.CharField(max_length=255)),
                ("banner_text", models.TextField()),
                ("banner_button_text", models.CharField(max_length=40)),
                ("banner_button_link", models.URLField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="only_one_active_banner",
                    )
                ],
            },
        ),
    ]
