# Generated by Django 5.1.1 on 2024-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerconfig",
            name="banner_button_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bannerconfig",
            name="banner_button_text",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="bannerconfig",
            name="banner_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bannerconfig",
            name="banner_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
