# Run using `docker-compose up`
networks:
  bc2_net_overlay:
    driver: bridge
    external: true

services:

  bc2-doctor:
    image: freelawproject/doctor:latest
    container_name: "bc2-doctor"
    networks:
      - bc2_net_overlay
    ports:
      - 5050:5050

  bc2-postgresql:
    container_name: bc2-postgresql
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bots"
    networks:
      - bc2_net_overlay

  bc2-redis:
    container_name: bc2-redis
    image: redis:7-alpine
    networks:
      - bc2_net_overlay


  bc2-rq:
    container_name: bc2-rq
    build:
      dockerfile: docker/django/Dockerfile
      context: ../../
      target: rq
      args:
        - BUILD_ENV=dev
    depends_on:
      - bc2-postgresql
      - bc2-doctor
      - bc2-redis
    volumes:
      - ../..:/opt/bigcases2
    networks:
      - bc2_net_overlay
    env_file:
      - ../../.env.dev

  bc2-tailwind-reload:
    container_name: bc2-tailwind-reload
    build:
      dockerfile: docker/django/Dockerfile
      context: ../../
      target: tailwind-reload-dev
      args:
        - BUILD_ENV=dev
    volumes:
      - ../..:/opt/bigcases2
    networks:
      - bc2_net_overlay
    env_file:
      - ../../.env.dev
    tty: true

  bc2-django:
    container_name: bc2-django
    build:
      dockerfile: docker/django/Dockerfile
      context: ../../
      target: web-dev
      args:
        - BUILD_ENV=dev
    depends_on:
      - bc2-tailwind-reload
      - bc2-postgresql
      - bc2-doctor
      - bc2-redis
    volumes:
      - ../..:/opt/bigcases2
    ports:
      - "8888:8000"
    networks:
      - bc2_net_overlay
    env_file:
      - ../../.env.dev
