# Generated by Django 4.1.7 on 2023-06-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="botsuggestion",
            old_name="name",
            new_name="bot_name",
        ),
        migrations.RenameField(
            model_name="botsuggestion",
            old_name="use_case",
            new_name="purpose",
        ),
        migrations.AddField(
            model_name="botsuggestion",
            name="is_curator",
            field=models.BooleanField(
                default=True,
                help_text="whether the user would want to curate the bot or not",
            ),
        ),
        migrations.AddField(
            model_name="botsuggestion",
            name="suggested_curators",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Users suggested for bot curation",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="botsuggestion",
            name="user_email",
            field=models.EmailField(
                default="",
                help_text="The email address of the user",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="botsuggestion",
            name="user_expertise",
            field=models.TextField(
                default="",
                help_text="Description of the user's skills or knowledge in the field",
            ),
        ),
        migrations.AddField(
            model_name="botsuggestion",
            name="user_full_name",
            field=models.CharField(
                default="",
                help_text="The full name of the user",
                max_length=150,
            ),
        ),
    ]
