# Generated by Django 4.1.5 on 2023-01-20 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "court",
                    models.CharField(
                        help_text="The court where the upload was from",
                        max_length=100,
                    ),
                ),
                (
                    "docket_number",
                    models.CharField(
                        help_text="The docket numbers of a case",
                        max_length=100,
                    ),
                ),
                (
                    "bcb1_description",
                    models.CharField(
                        help_text="Name from the list of cases used in the first version",
                        max_length=200,
                    ),
                ),
                (
                    "in_bcb1",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a Docket was used in the first version",
                    ),
                ),
                (
                    "cl_case_title",
                    models.TextField(
                        help_text="the highest quality case name."
                    ),
                ),
                (
                    "cl_docket_id",
                    models.IntegerField(
                        help_text="The docket id from Courtlistener db."
                    ),
                ),
                (
                    "cl_slug",
                    models.TextField(
                        help_text="URL that the document should map to (the slug)."
                    ),
                ),
                (
                    "cl_alerts",
                    models.BooleanField(
                        help_text="Whether a document has alerts turn on."
                    ),
                ),
                (
                    "judges",
                    models.ManyToManyField(
                        help_text="The judges for the case.",
                        related_name="cases",
                        to="people.judge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocketEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "cl_docket_entry_id",
                    models.IntegerField(
                        help_text="The entry id from Courtlistener db."
                    ),
                ),
                (
                    "entry_number",
                    models.IntegerField(
                        help_text="The docket entry number for the document."
                    ),
                ),
                (
                    "pacer_sequence_number",
                    models.IntegerField(
                        help_text="A field used for ordering the docket entries on a docket."
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        help_text="Foreign key as a relation to the Docket object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docket_entries",
                        to="cases.docket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "attachment_number",
                    models.IntegerField(
                        help_text="If the file is an attachment, This field stores the attachment number in RECAP docket."
                    ),
                ),
                (
                    "docket",
                    models.ForeignKey(
                        help_text="Foreign Key to the Docket object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.docket",
                    ),
                ),
                (
                    "docket_entry",
                    models.ForeignKey(
                        help_text="Foreign Key to the DocketEntry object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.docketentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentThumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="The moment when the item was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        help_text="Page number of the thumbnail."
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        help_text="URL to the file on CL storage.",
                        upload_to="",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="'Foreign Key to the Document object.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="cases.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
