# Generated by Django 4.1.5 on 2023-01-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docket",
            name="cl_alerts",
            field=models.BooleanField(
                default=False,
                help_text="Whether a document has alerts turn on.",
            ),
        ),
    ]
