# Generated by Django 4.1.5 on 2023-01-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_docket_cl_alerts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docket",
            name="cl_docket_id",
            field=models.IntegerField(
                help_text="The docket id from Courtlistener db.", null=True
            ),
        ),
    ]
